---

- name: "Update local apt repo"
  become: true
  apt:
    update_cache: yes
    
- name: "Update apt packages"
  become: true
  apt:
    upgrade: yes
    
- name: "Remove stale dependencies"
  become: true
  apt:
    autoremove: yes
    
- name: "Install dependencies [nodejs and npm]"
  become: true
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes
   
  # pm = process manager 
- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

