# ---
# - name: "update local apt repo."
#   become: true
#   apt:
#     update_cache: yes

# - name: "upgrade apt packages"
#   become: true
#   apt:
#     upgrade: yes

# - name: "remove stale dependencies"
#   become: true
#   apt:
#     autoremove: yes

# - name: "install dependencies [nodejs and npm]."
#   become: true
#   apt:
#     name: ["nodejs", "npm"]
#     state: latest
#     update_cache: yes

# - name: "install pm2"
#   become: true
#   npm:
#     name: pm2
#     global: yes
#     production: yes
#     state: present

# - name: "Copy artifact into Instance" 
#   become: true
#   copy:
#     src: ~/project/artifact.tar.gz
#     dest: /home/ubuntu/artifact.tar.gz


# - name: "Start app"
#   become: true
#   shell: |
#     cd /home/ubuntu
#     tar xzvf artifact.tar.gz
#     npm install
#     npm run build
#     pm2 stop all
#     pm2 start npm -- start
    

---
- name: "Update local apt repo"
  become: true
  apt:
    update_cache: yes

- name: "Upgrade apt packages"
  become: true
  apt:
    upgrade: yes

- name: "Install dependencies [nodejs & npm]"
  become: true
  apt:
    name: ["nodejs","npm"]
    state: latest
    update_cache: yes

- name: "Install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: Configure pm2 to start as service
  become: true
  shell: |
    sudo su -c "env PATH=$PATH:usr/local/bin pm2 startup systemd -u ubuntu --hp /home/ubuntu"
    pm2 save
    
- name: Create Backend Directory
  file:
    path: /home/ubuntu/backend
    state: directory

- name: Copy artifact into instance 
  become: true
  copy:
    src: ~/project/artifact.tar.gz
    dest: /home/ubuntu/backend 

- name: Extract artifact.tar.gz
  unarchive:
    src: ~/project/artifact.tar.gz
    dest: /home/ubuntu/backend   

- name: "Installing Node Dependencies"
  shell: |
    cd /home/ubuntu/backend
    sudo npm i
    
- name: Start the app
  become: true
  shell: |
    cd /home/ubuntu/backend/dist
    pm2 stop all
    pm2 start npm -- start main.js
  register: execute_node

- name: "Remove stale dependencies"
  become: true
  apt:
    autoremove: yes


- name: Print message
  debug:
      msg: "{{ execute_node.stdout_lines }}"